#!/usr/bin/env python3
"""Deterministic generator for the replay corpus (TOOL-039, #110).

The recorded production failure signatures live outside the repo (durability
doctrine, AGENTS.md); what is committed under corpus/ is the reconstruction of
each incident's decision-relevant trace, regenerated byte-identically by this
script. Idiom follows evals/fixtures/gen_*.py: `python gen_corpus.py <out_dir>`.

Every incident is validated against replay_schema before being written — a
generator bug fails here, not in CI.

Python 3.10, standard library only.
"""
import json
import sys
from pathlib import Path

from replay_schema import validate_case

COM_STACK = ["combase!CoWaitForMultipleHandles",
             "msxml6!Document::load",
             "python310!PyEval_EvalFrameDefault"]
IDLE_STACK = ["ntdll!NtWaitForSingleObject",
              "python310!PyEval_EvalFrameDefault"]
IO_STACK = ["ntdll!NtReadFile", "python310!PyEval_EvalFrameDefault"]


def _open():
    return {"t": 0, "type": "dispatch_open"}


def _prog(t, n):
    return {"t": t, "type": "progress", "bytes_written": n}


def _probe(t, cpu, age, stacks=None):
    return {"t": t, "type": "probe", "probe_ok": True, "cpu_percent": cpu,
            "last_write_age_s": age, "stack_frames": stacks}


def _probe_failed(t):
    # 2026-09-16/17: the monitor's own probe never completed (SMB-stat hang).
    return {"t": t, "type": "probe", "probe_ok": False}


def _done(t, channel="envelope_completed"):
    return {"t": t, "type": "completion_evidence", "channel": channel}


def _case(case_id, date, cls, note, events, expect, timeout_s=1800,
          max_minutes=None):
    dispatch = {"agent": "kimi-worker", "timeout_s": timeout_s}
    if max_minutes is not None:
        dispatch["max_minutes"] = max_minutes
    return {"schema_version": 1, "case_id": case_id, "incident_date": date,
            "class": cls, "source_note": note, "dispatch": dispatch,
            "events": events, "expect": expect}


INCIDENTS = [
    # ── 2026-09-01 x2: succeeded 2-3 min before the stall kill ──────────
    _case(
        "2026-09-01-completion-stall-kill-a", "2026-09-01",
        "completion_before_stall_kill",
        "Job A succeeded at t=1740; the stall heuristic killed it at ~t=1920, "
        "3 min after success. Post-completion the idle worker reads as a wedge "
        "(silent writes, idle stack) to any predicate that does not check "
        "completion evidence first.",
        [_open(),
         _prog(120, 4096), _probe(300, 18.0, 60),
         _prog(600, 32768), _probe(900, 22.5, 300),
         _prog(1200, 131072), _probe(1500, 15.1, 300),
         _prog(1740, 262144), _done(1740),
         _probe(1800, 0.4, 60, IDLE_STACK),
         _probe(1920, 0.2, 180, IDLE_STACK)],
        {"kill": False}),
    _case(
        "2026-09-01-completion-stall-kill-b", "2026-09-01",
        "completion_before_stall_kill",
        "Job B the same night: success at t=2280, stall kill at ~t=2400 — "
        "2 min after success.",
        [_open(),
         _prog(300, 8192), _probe(600, 19.4, 300),
         _prog(900, 65536), _probe(1200, 21.0, 300),
         _prog(1500, 196608), _probe(1800, 16.8, 300),
         _prog(2100, 229376), _done(2280),
         _probe(2340, 0.6, 60, IDLE_STACK),
         _probe(2400, 0.3, 120, IDLE_STACK)],
        {"kill": False}),
    # ── 2026-09-12: killed 46 s after success ───────────────────────────
    _case(
        "2026-09-12-killed-46s-after-success", "2026-09-12",
        "killed_after_success",
        "Envelope completed at t=1500; the kill landed 46 s later. Any "
        "post-completion reaction window shorter than the kill path is fatal.",
        [_open(),
         _prog(300, 4096), _probe(600, 17.7, 300),
         _prog(900, 45056), _probe(1200, 20.3, 300),
         _prog(1500, 90112), _done(1500),
         _probe(1546, 0.1, 46, IDLE_STACK)],
        {"kill": False}),
    # ── 2026-09-16/17: monitor measurement failure → abstain ────────────
    _case(
        "2026-09-16-monitor-smb-self-hang", "2026-09-16",
        "monitor_measurement_failure",
        "Monitor wedged stat-ing the SMB-hosted run dir; the CPU counter "
        "returned -1 at t=900 and the t=1500 probe never completed. The "
        "worker kept writing throughout — every kill input was a measurement "
        "artifact.",
        [_open(),
         _prog(300, 4096), _probe(300, 14.2, 45),
         _prog(600, 20480), _probe(900, -1.0, -1),
         _prog(1200, 45056), _probe_failed(1500),
         _prog(1800, 90112)],
        {"kill": False, "measurement_degraded": True}),
    _case(
        "2026-09-17-impossible-write-ages-negative-cpu", "2026-09-17",
        "monitor_measurement_failure",
        "Write age 999999 s at t=960 — older than the dispatch itself — and "
        "CPU -3.5%: physically impossible samples must read as "
        "measurement_degraded, never as a stalled worker.",
        [_open(),
         _prog(240, 4096), _probe(240, 22.0, 30),
         _prog(480, 16384), _probe(960, -3.5, 999999),
         _prog(1440, 32768), _probe_failed(1680)],
        {"kill": False, "measurement_degraded": True}),
    # ── 2026-08-25 x3: MaxMinutes wall-clock kills of a healthy run ─────
    _case(
        "2026-08-25-maxminutes-slow-vm-kill-1", "2026-08-25",
        "maxminutes_healthy_slow_run",
        "First of three MaxMinutes wall-clock kills of one healthy run on a "
        "slow VM. Progress stayed fresh through the 45-minute backstop; the "
        "wall clock was the only kill input.",
        [_open(),
         _prog(600, 8192), _probe(600, 3.5, 220),
         _prog(1200, 16384), _probe(1200, 4.1, 300),
         _prog(1800, 24576), _probe(1800, 5.9, 240),
         _prog(2400, 32768), _probe(2400, 4.4, 480),
         _prog(3000, 40960), _probe(3000, 6.8, 610),
         _probe(3300, 5.2, 300)],
        {"kill": False, "backstop_crossed": True}, max_minutes=45),
    _case(
        "2026-08-25-maxminutes-slow-vm-kill-2", "2026-08-25",
        "maxminutes_healthy_slow_run",
        "Second MaxMinutes kill after the restart; slower still — write ages "
        "up to 700 s — and still live at every checkpoint.",
        [_open(),
         _prog(600, 4096), _probe(600, 2.8, 400),
         _prog(1500, 12288), _probe(1500, 6.1, 620),
         _prog(2100, 20480), _probe(2100, 5.5, 700),
         _prog(2700, 28672), _probe(2700, 3.9, 450),
         _prog(3300, 36864), _probe(3300, 6.4, 650),
         _probe(3600, 4.7, 300)],
        {"kill": False, "backstop_crossed": True}, max_minutes=45),
    _case(
        "2026-08-25-maxminutes-slow-vm-kill-3", "2026-08-25",
        "maxminutes_healthy_slow_run",
        "Third kill; the worker sat in the same IO read stack across probes. "
        "Identical stacks with fresh writes are not a wedge.",
        [_open(),
         _prog(600, 4096), _probe(600, 4.9, 310, IO_STACK),
         _prog(1200, 10240), _probe(1200, 5.3, 420, IO_STACK),
         _prog(1800, 16384), _probe(1800, 5.0, 480, IO_STACK),
         _prog(2400, 22528), _probe(2400, 6.2, 540, IO_STACK),
         _prog(3000, 28672), _probe(3000, 5.8, 590, IO_STACK),
         _probe(3600, 4.2, 480, IO_STACK)],
        {"kill": False, "backstop_crossed": True}, max_minutes=45),
    # ── CONTROL 2026-09-25 attempts 06/07: genuine COM wedge → kill ─────
    _case(
        "2026-09-25-com-wedge-attempt06", "2026-09-25",
        "control_genuine_wedge",
        "CONTROL. Attempt 06: genuine COM wedge — busy CPU, zero writes for "
        "25 min (last write t=600, kill expected t=2100), identical COM stack "
        "frames across probes. Must kill WITH stack evidence.",
        [_open(),
         _prog(300, 4096), _prog(600, 10240),
         _probe(900, 24.0, 300, COM_STACK),
         _probe(1200, 26.5, 600, COM_STACK),
         _probe(1500, 31.2, 900, COM_STACK),
         _probe(1800, 28.4, 1200, COM_STACK),
         _probe(2100, 33.1, 1500, COM_STACK)],
        {"kill": True, "reason": "confirmed_wedge",
         "kill_window_s": [2000, 2200], "evidence_keys": ["stack_frames"]}),
    _case(
        "2026-09-25-com-wedge-attempt07", "2026-09-25",
        "control_genuine_wedge",
        "CONTROL. Attempt 07: same wedge signature — writes silent from "
        "t=900, kill expected at t=2400 (25 min of silence).",
        [_open(),
         _prog(300, 4096), _prog(900, 12288),
         _probe(1200, 21.0, 300, COM_STACK),
         _probe(1500, 25.5, 600, COM_STACK),
         _probe(1800, 29.8, 900, COM_STACK),
         _probe(2100, 27.3, 1200, COM_STACK),
         _probe(2400, 30.6, 1500, COM_STACK)],
        {"kill": True, "reason": "confirmed_wedge",
         "kill_window_s": [2300, 2500], "evidence_keys": ["stack_frames"]}),
]


def main(out_dir):
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for case in INCIDENTS:
        validate_case(case)
        payload = (json.dumps(case, indent=2, sort_keys=True) + "\n"
                   ).encode("utf-8")
        # LF bytes explicitly: byte-stability must survive core.autocrlf.
        (out / f"{case['case_id']}.json").write_bytes(payload)


if __name__ == "__main__":
    main(sys.argv[1])
